### ISSUE TITLE
Code for `array_agg` support needs cleanup

### ISSUE THREAD

**Issue by tysonclugg** [jazzband/django-ddp#3]
The code around https://github.com/commoncode/django-ddp/blob/develop/dddp/api.py#L49 for supporting the `array_agg` PostgreSQL aggregate function works for Django 1.7 and 1.8, but it's ugly and needs to be cleaned up.

**Comment by tysonclugg** [comment]
Django DDP will drop support for Django 1.7 in December, in line with Django dropping extended support then (documented at https://www.djangoproject.com/download/#supported-versions).  When the Django Foundation officially drop support for Django 1.7, then the code can be cleaned up.

**Comment by schinckel** [comment]
Related: can the django-dbarray requirement be dropped in favour of `django.contrib.postgres` Array field implementation?

**Comment by schinckel** [comment]
Oh, the `django.contrib.postgres` implementation of `array_agg` is 1.9+ only.
