### ISSUE TITLE
Cannot run tox on fresh checkout (needs meteor installed?)

### ISSUE THREAD

**Issue by schinckel** [jazzband/django-ddp#37]
IMHO, it should be possible to check out the project on a brand new machine, and run tox.

I believe there is some requirement for meteor to be installed?

**Comment by tysonclugg** [comment]
I guess it comes down to the difference between using and developing django-ddp.  The test suite includes a Meteor project, so I think it's fair that you need Meteor to run the tests - unless we're in favour of committing the Meteor compiled JavaScript into the repo.  Your thoughts @schinckel ?

**Comment by tysonclugg** [comment]
The follow up question that arises is what should we include in the `sdist` that gets uploaded to PyPi?

**Comment by schinckel** [comment]
I was wondering if there should be a documentation section about developing. I don't have any issues about requiring meteor, it just wasn't obvious (even from the traceback, until I really looked hard) that the problem was that it needed to be installed.
