### ISSUE TITLE
Deployment via gunicorn?

### ISSUE THREAD

**Issue by rantecki** [jazzband/django-ddp#51]
Hi there,

Firstly, thanks for working on this project.

I'm wondering if anyone is using this in production, and/or if there's any reasons to not consider it for production use at this point?

Also on that topic, does anyone have any example code on how this would be deployed in a production environment using gunicorn?  I'm guessing it's more complicated than simply pointing gunicorn at the dddp command.

Many thanks,
Richard

**Comment by tysonclugg** [comment]
Hi Richard,

I'm only aware of one project using this on production: www.meerqat.com.au

It is intended that django-ddp should serve HTTP requests (from behind your public facing web server) without using gunicorn at all - see `dddp --help` for details.

I'm closing this issue as you've phrased it as a question which has been answered, please open a new issue if you need gunicorn support specifically.

Cheers,
Tyson.

**Comment by rantecki** [comment]
Thanks for the response.  I guess I was thrown off a bit by reading that gunicorn supports gevent and assumed that it could be used for this kind of thing.  Automated management of multiple workers would be the main driver to use gunicorn in front of this.

I haven't found a great deployment solution yet.  I'm currently running dddp as a separate process to my main django app and routing /websocket/ to it via nginx.  That seems to work ok for the moment although it's not ideal.
