### ISSUE TITLE
Stable enough for long-term usage?

### ISSUE THREAD

**Issue by nerdoc** [jazzband/django-ddp#55]
This is a question, no bug.
1. I'm just asking wether django-ddp is considered stable enough to be used for a medical application, where data loss/failure is a more-or-less no-go, and should be maintainable for many years.
How stable is django-ddp considered to be for that?
Would you recommend it for using in a "data loss critical" environment?

I know that this question is a bit broad, and answers maybe opinion-based, but I want to ask it nevertheless.

2. Is django-ddp on the server and python-ddp on the client a stable option? Any experiences here?
Thank you very much.

**Comment by dburles** [comment]
I'd suggest https://www.apollodata.com/

**Comment by nerdoc** [comment]
Hm. You'd *suggest* using Apollo *instead* of django-ddp? Could you explain a bit more?

**Comment by dburles** [comment]
Yes, definitely. We probably would have use it instead of creating django-ddp had it existed back then.

**Comment by nerdoc** [comment]
Thanks.
