### ISSUE TITLE
Python 3 support with gevent beta

### ISSUE THREAD

**Issue by yunti** [jazzband/django-ddp#6]
I suppose someone had to ask for it. But it would be great to have python 3 support now that gevent==1.1b2 has it.  (well you did mention it in your recent pycon Oz talk)

**Comment by tysonclugg** [comment]
As per https://github.com/commoncode/django-ddp/blob/develop/setup.py#L34 it's already supported.

My understanding is that setup.py defines abstract requirements, while requirements.txt has concrete requirements.  The concrete requirements in django-ddp are meant to be installed as part of the test suite, and as such if the tests pass they are the officially supported.  The specific Python version is not specified in requirements.txt.

As an aside, I've been working on PyPy support as well.  :smiley:

**Comment by yunti** [comment]
Superb thanks for the update
