### ISSUE TITLE
What is your experience using this app?

### ISSUE THREAD

**Issue by thebarty** [jazzband/django-ddp#8]
Hi guys,

I am looking into meteor right now and the only thing keeping me away is the nosql mongodb database.
This module looks like the solution!!! 

Can you tell me about your experience using it?
Are you using it in production?
Are you happy with it?
Are there any problems that might occur?
Do all meteor-functions work?

I'd really love to hear some feedback.

Kind regards
Mikey

**Comment by tysonclugg** [comment]
Hi Mikey,

Django DDP is in production use on https://meerqat.com.au/ as the MEERQAT team were gracious and allowed django-ddp to be released under the MIT license.

As the author, I'm very happy with the design decisions I have made, and relatively happy with the way development has progressed.  The things that I currently consider as blockers to a 1.0 (production/stable) release are:
- Good documentation.
- Good automated tests with coverage across the supported dependency matrix (eg: Python 2.7 / 3.3 / 3.4 / 3.5, Django 1.7/1.8/1.9, etc).
- A stable API (I have some minor changes planned for publications).
- Perhaps extending support to other database backends aside from PostgreSQL (though I have reservations if this is a good idea as the current architecture ensures change messages are only delivered when database transactions are successfully committed).
- Support for distributing load across multiple CPU cores in an efficient manner.

The problems you are likely to face as a developer at this early stage are primarily related to the lack of documentation, and infrequent backwards incompatible API changes.

As the client side is still running Meteor in exactly the same way (the same HTML and JavaScript is served to the browser), nearly all features work exactly as expected.  The only functions I can see looking at the current Meteor docs (v1.2.0) that don't work are:
- [`Accounts.logoutOtherClients`](http://docs.meteor.com/#/full/meteor_logoutotherclients) - this should be achievable.
- [`Accounts.loginWith<service>`](http://docs.meteor.com/#/full/meteor_loginwithexternalservice) - looks somewhat challenging, but achievable in the longer term.
- Many of the features from [Passwords](http://docs.meteor.com/#/full/accounts_passwords), however the following functions do work: `changePassword`, `createUser`, `forgotPassword`, `login`, `logout` and `resetPassword` - The important functions work, more can be done relatively easily.

As server side code is entirely Python/Django, packages such as [Email](http://docs.meteor.com/#/full/email) don't make sense in this context (use [`django.core.mail`](https://docs.djangoproject.com/en/1.8/topics/email/) instead).

My goal is to address many of the points above and schedule a 1.0 release to coincide with the release of Django 1.9 in December this year (2015).

I hope I've answered all your questions, feel free to raise new issues on anything you see here or think of later.

Regards,
Tyson.
