### ISSUE TITLE
Do you have a base project with this working?

### ISSUE THREAD

**Issue by dan-gamble** [jazzband/django-ddp#9]
Just curious to see what a project structure where you mesh these 2 would look like. This would be project paradise for me if i can get this working :)

**Comment by tysonclugg** [comment]
There is [an example project layout in the test suite](https://github.com/commoncode/django-ddp/tree/develop/dddp/test).  Feel free to log another issue against the lack of documentation...  ;-)

**Comment by dan-gamble** [comment]
That looks very helpful, i tried it last night but had no success! Will try it again with this test project you have to try it out :)

**Comment by dan-gamble** [comment]
Got it working! Showing the TODO's at least :)

Is there a way to get the polling working i.e if i add a Task through the `./manage.py shell` then it will auto show on the frontend?

**Comment by dan-gamble** [comment]
Scratch that, if i clone this repo and use it without moving it out of test it's fine. If i move it into it's own project it doesn't seem to work. Will investigate further :)
